// Test configuration that bypasses validation
export const testConfig = {
  USE_LOCAL_DB: true,
  TURSO_DATABASE_URL: undefined,
  TURSO_AUTH_TOKEN: undefined,
  BETTER_AUTH_SECRET: 'test-secret-that-is-at-least-32-characters-long-for-testing',
  BETTER_AUTH_URL: 'http://localhost:4321',
  GROQ_API_KEY: 'test-groq-api-key',
  NODE_ENV: 'test' as const,
  PORT: 4321,
  ENABLE_DEBUG_LOGS: false,
  RATE_LIMIT_TRANSCRIPTION: 5,
  RATE_LIMIT_NOTES: 30,
  MAX_AUDIO_FILE_SIZE: 10,
  USE_CDN: false,
  CDN_BASE_URL: undefined,
  SENTRY_DSN: undefined,
  GA_TRACKING_ID: undefined,
  SMTP_HOST: undefined,
  SMTP_PORT: undefined,
  SMTP_USER: undefined,
  SMTP_PASSWORD: undefined,
  FROM_EMAIL: undefined,
};